site_name: Krail

pages:
- Home: 'index.md'
- Tutorial:
  - 'Getting Started': 'tutorial-getting-started.md'
  - 'Pages and Navigation': 'tutorial-pages-navigation.md'
  - 'UI & Theme': 'tutorial-ui-theme.md'
  - 'User Notification': 'tutorial-user-notification.md'
  - 'Options and UserHierarchies': 'tutorial-options.md'
  - 'Configuration from Ini file': 'tutorial-configuration-from-ini.md'
  - 'User Access Control': 'tutorial-uac.md'
  - 'I18N': 'tutorial-i18n.md'
  - 'I18N, Components and Validation': 'tutorial-i18n-components-validation.md'
  - 'Persistence - JPA': 'tutorial-persistence-jpa.md'
  - 'Guice Scopes': 'tutorial-guice-scopes.md'
  - 'Event Bus': 'tutorial-event-bus.md'
  - 'Services': 'tutorial-services.md'
  - 'Vaadin Push': 'tutorial-push.md'
  - 'Eclipse IDE': 'tutorial-eclipse.md'
  - 'Create User Hierarchy': 'tutorial-create-hierarchy.md'
- Developer Guide:
  - 'Introduction': 'devguide-introduction.md'
  - 'Krail Configuration Overview': 'devguide-configuration-overview.md'
  - 'Pages and Navigation': 'devguide-pages-navigation.md'
  - 'Options and UserHierarchies': 'devguide-options-hierarchies.md'
  - 'Developer Guide - I18N': 'devguide-i18n.md'
  - 'Guice Scopes': 'devguide-guice-scopes.md'
  - 'Event Bus': 'devguide-eventbus.md'
  - 'Validation': 'devguide-validation.md'
  - 'Persistence providers': 'devguide-persistence.md'
- Glossary: 'glossary.md'
- Licence: 'license.md'

theme: readthedocs



